### ISSUE TITLE
Validation des inputs incorrect

### ISSUE THREAD

**Issue by lahaxearnaud** [EnMarche/simuletataxe.fr#29]
Les données saisies dans l'URL ne sont pas validées.

[https://simuletataxe.fr/result/Paie%20ta/validation/des%20inputs](https://simuletataxe.fr/result/Paie%20ta/validation/des%20inputs)

**Comment by benoitzohar** [comment]
Apparement l’injection de script est tout de même bloquée, ce qui est une bonne nouvelle en soit.
Tu paies ta PR @lahaxearnaud ? 😎

**Comment by tgalopin** [comment]
Merci du feedback @lahaxearnaud !
